//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picross_LevelEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bToolTipAvilable {
            get {
                return ((bool)(this["bToolTipAvilable"]));
            }
            set {
                this["bToolTipAvilable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo ciSelectedLanguage {
            get {
                return ((global::System.Globalization.CultureInfo)(this["ciSelectedLanguage"]));
            }
            set {
                this["ciSelectedLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bGridLineShow {
            get {
                return ((bool)(this["bGridLineShow"]));
            }
            set {
                this["bGridLineShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sExportGraphPath {
            get {
                return ((string)(this["sExportGraphPath"]));
            }
            set {
                this["sExportGraphPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphAddSizeToName {
            get {
                return ((bool)(this["bExportGraphAddSizeToName"]));
            }
            set {
                this["bExportGraphAddSizeToName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bExportGraphUsePng {
            get {
                return ((bool)(this["bExportGraphUsePng"]));
            }
            set {
                this["bExportGraphUsePng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphUseBmp {
            get {
                return ((bool)(this["bExportGraphUseBmp"]));
            }
            set {
                this["bExportGraphUseBmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphUseTif {
            get {
                return ((bool)(this["bExportGraphUseTif"]));
            }
            set {
                this["bExportGraphUseTif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphUseGif {
            get {
                return ((bool)(this["bExportGraphUseGif"]));
            }
            set {
                this["bExportGraphUseGif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphUseJpg {
            get {
                return ((bool)(this["bExportGraphUseJpg"]));
            }
            set {
                this["bExportGraphUseJpg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphUseWpg {
            get {
                return ((bool)(this["bExportGraphUseWpg"]));
            }
            set {
                this["bExportGraphUseWpg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphPngInter {
            get {
                return ((bool)(this["bExportGraphPngInter"]));
            }
            set {
                this["bExportGraphPngInter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportGraphTifWithZip {
            get {
                return ((bool)(this["bExportGraphTifWithZip"]));
            }
            set {
                this["bExportGraphTifWithZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte byteExportGraphJpgQuality {
            get {
                return ((byte)(this["byteExportGraphJpgQuality"]));
            }
            set {
                this["byteExportGraphJpgQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte byteExportGraphWpgQuality {
            get {
                return ((byte)(this["byteExportGraphWpgQuality"]));
            }
            set {
                this["byteExportGraphWpgQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int iExportGraphOutputScale {
            get {
                return ((int)(this["iExportGraphOutputScale"]));
            }
            set {
                this["iExportGraphOutputScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bIsSimple {
            get {
                return ((bool)(this["bIsSimple"]));
            }
            set {
                this["bIsSimple"] = value;
            }
        }
    }
}
