//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picross_LevelEditor.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Picross_LevelEditor.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About Program.
        /// </summary>
        public static string sAboutProgram {
            get {
                return ResourceManager.GetString("sAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add New Color.
        /// </summary>
        public static string sAddNewColor {
            get {
                return ResourceManager.GetString("sAddNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Background Color.
        /// </summary>
        public static string sBackgroundColor {
            get {
                return ResourceManager.GetString("sBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Basic Level Settings.
        /// </summary>
        public static string sBasicLevelSettings {
            get {
                return ResourceManager.GetString("sBasicLevelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string sCancel {
            get {
                return ResourceManager.GetString("sCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cells Count.
        /// </summary>
        public static string sCellsCount {
            get {
                return ResourceManager.GetString("sCellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear color of tile.
        /// </summary>
        public static string sClearColorOfTile {
            get {
                return ResourceManager.GetString("sClearColorOfTile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color ID.
        /// </summary>
        public static string sColorId {
            get {
                return ResourceManager.GetString("sColorId", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confiramtion of operation.
        /// </summary>
        public static string sConfiramtionOfOperation {
            get {
                return ResourceManager.GetString("sConfiramtionOfOperation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current Cell.
        /// </summary>
        public static string sCurrentCell {
            get {
                return ResourceManager.GetString("sCurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleta All Cells.
        /// </summary>
        public static string sDeletaAllCells {
            get {
                return ResourceManager.GetString("sDeletaAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete This Color Option.
        /// </summary>
        public static string sDeleteThisColorOption {
            get {
                return ResourceManager.GetString("sDeleteThisColorOption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu English.
        /// </summary>
        public static string sEnglish {
            get {
                return ResourceManager.GetString("sEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configuration File of program not exist or it is corrupted.
        ///Program will open with default settings.
        ///If you open first time this program, pleas ignore this problem.
        ///If this problem occur every time during opening a program, please start program with Administrator Rights..
        /// </summary>
        public static string sErrorConfigFileNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Problem with Configuration File.
        /// </summary>
        public static string sErrorConfigFileNoExistTitle {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a correct level name..
        /// </summary>
        public static string sErrorIncorrectNameMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incorrect level name.
        /// </summary>
        public static string sErrorIncorrectNameTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a correct level path..
        /// </summary>
        public static string sErrorIncorrectPathMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incorrect level path.
        /// </summary>
        public static string sErrorIncorrectPathTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manual cannot be open properly. Please check you PC can open PDF files.
        ///
        ///If PC can open PDF files pleas make following steps:
        ///1. Check program folder, if contains folder &quot;Manuals&quot;.
        ///2.  Check &quot;Manuals&quot; folder contains PDF file &quot;Flip Block 3D - Level Editor (User Manual).pdf&quot;.
        ///
        ///If any step is not met, please contact with person who distrbute this program..
        /// </summary>
        public static string sErrorManualOpenMessage {
            get {
                return ResourceManager.GetString("sErrorManualOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error during open manual.
        /// </summary>
        public static string sErrorManualOpenTittle {
            get {
                return ResourceManager.GetString("sErrorManualOpenTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level cannot be opened!
        ///File is corrupted..
        /// </summary>
        public static string sErrorOpenLevelMessage {
            get {
                return ResourceManager.GetString("sErrorOpenLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open level error.
        /// </summary>
        public static string sErrorOpenLevelTittle {
            get {
                return ResourceManager.GetString("sErrorOpenLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The level path does not exist..
        /// </summary>
        public static string sErrorPathNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorPathNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No exist level path.
        /// </summary>
        public static string sErrorPathNoExistTittle {
            get {
                return ResourceManager.GetString("sErrorPathNoExistTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was not saved correct!
        ///Some unxpected error occure..
        /// </summary>
        public static string sErrorSaveLevelMessage {
            get {
                return ResourceManager.GetString("sErrorSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error during save level.
        /// </summary>
        public static string sErrorSaveLevelTittle {
            get {
                return ResourceManager.GetString("sErrorSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit.
        /// </summary>
        public static string sExit {
            get {
                return ResourceManager.GetString("sExit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string sFile {
            get {
                return ResourceManager.GetString("sFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Finish.
        /// </summary>
        public static string sFinish {
            get {
                return ResourceManager.GetString("sFinish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game Level.
        /// </summary>
        public static string sGameLevel {
            get {
                return ResourceManager.GetString("sGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Height (Y).
        /// </summary>
        public static string sHeight_InBracketY {
            get {
                return ResourceManager.GetString("sHeight_InBracketY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        public static string sHelp {
            get {
                return ResourceManager.GetString("sHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id of color.
        /// </summary>
        public static string sIdOfColor {
            get {
                return ResourceManager.GetString("sIdOfColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import From Picture.
        /// </summary>
        public static string sImportFromPicture {
            get {
                return ResourceManager.GetString("sImportFromPicture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New game level was created!.
        /// </summary>
        public static string sInfoNewLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New level confirmation.
        /// </summary>
        public static string sInfoNewLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was opened correct!.
        /// </summary>
        public static string sInfoOpenLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open level confirmation.
        /// </summary>
        public static string sInfoOpenLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was saved correct!.
        /// </summary>
        public static string sInfoSaveLevelMessage {
            get {
                return ResourceManager.GetString("sInfoSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save level confiramtion.
        /// </summary>
        public static string sInfoSaveLevelTittle {
            get {
                return ResourceManager.GetString("sInfoSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        public static string sLanguage {
            get {
                return ResourceManager.GetString("sLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Dimension.
        /// </summary>
        public static string sLevelDimension {
            get {
                return ResourceManager.GetString("sLevelDimension", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Names.
        /// </summary>
        public static string sLevelNames {
            get {
                return ResourceManager.GetString("sLevelNames", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Editor.
        /// </summary>
        public static string sLevelsEditor {
            get {
                return ResourceManager.GetString("sLevelsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu List of cells.
        /// </summary>
        public static string sListOfCells {
            get {
                return ResourceManager.GetString("sListOfCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logic Pictures.
        /// </summary>
        public static string sLogicPicture {
            get {
                return ResourceManager.GetString("sLogicPicture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The &quot;Manual file&quot; cannot be opened correctly.
        ///Please check the location of the program at where the manual file is stored.
        ///If you can’t find the manual file, please contact the person who distributed this program..
        /// </summary>
        public static string sManualFileMissingMessage {
            get {
                return ResourceManager.GetString("sManualFileMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manual file is missing.
        /// </summary>
        public static string sManualFileMissingTitle {
            get {
                return ResourceManager.GetString("sManualFileMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Marker Color.
        /// </summary>
        public static string sMarkerColor {
            get {
                return ResourceManager.GetString("sMarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Level.
        /// </summary>
        public static string sNewLevel {
            get {
                return ResourceManager.GetString("sNewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        public static string sOk {
            get {
                return ResourceManager.GetString("sOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Level.
        /// </summary>
        public static string sOpenLevel {
            get {
                return ResourceManager.GetString("sOpenLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Manual.
        /// </summary>
        public static string sOpenManual {
            get {
                return ResourceManager.GetString("sOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logic Pictures - Level Editor.
        /// </summary>
        public static string sPicross_LevelEditor {
            get {
                return ResourceManager.GetString("sPicross_LevelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polish.
        /// </summary>
        public static string sPolish {
            get {
                return ResourceManager.GetString("sPolish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Position X.
        /// </summary>
        public static string sPositionX {
            get {
                return ResourceManager.GetString("sPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Position Y.
        /// </summary>
        public static string sPositionY {
            get {
                return ResourceManager.GetString("sPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Preview Level.
        /// </summary>
        public static string sPreviewLevel {
            get {
                return ResourceManager.GetString("sPreviewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Path.
        /// </summary>
        public static string sProjectPath {
            get {
                return ResourceManager.GetString("sProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You are sure to delete this color tile option?.
        /// </summary>
        public static string sQuestionBeforeDeleteColor {
            get {
                return ResourceManager.GetString("sQuestionBeforeDeleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release Date.
        /// </summary>
        public static string sReleaseDate {
            get {
                return ResourceManager.GetString("sReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Level.
        /// </summary>
        public static string sSaveLevel {
            get {
                return ResourceManager.GetString("sSaveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Level as....
        /// </summary>
        public static string sSaveLevelAs3xDot {
            get {
                return ResourceManager.GetString("sSaveLevelAs3xDot", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Mode.
        /// </summary>
        public static string sSelectMode {
            get {
                return ResourceManager.GetString("sSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set Defoult View.
        /// </summary>
        public static string sSetDefoultView {
            get {
                return ResourceManager.GetString("sSetDefoultView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Bottom Status Bar.
        /// </summary>
        public static string sShowBottomStatusBar {
            get {
                return ResourceManager.GetString("sShowBottomStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show cells text info.
        /// </summary>
        public static string sShowCellsTextInfo {
            get {
                return ResourceManager.GetString("sShowCellsTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show grid lines on tiles panel.
        /// </summary>
        public static string sShowGridLines {
            get {
                return ResourceManager.GetString("sShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Left Panel.
        /// </summary>
        public static string sShowLeftPanel {
            get {
                return ResourceManager.GetString("sShowLeftPanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Right Panel.
        /// </summary>
        public static string sShowRightPanel {
            get {
                return ResourceManager.GetString("sShowRightPanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Tool Bar.
        /// </summary>
        public static string sShowToolBar {
            get {
                return ResourceManager.GetString("sShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tiles Natural Color.
        /// </summary>
        public static string sTilesNaturalColor {
            get {
                return ResourceManager.GetString("sTilesNaturalColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used Colors.
        /// </summary>
        public static string sUsedColors {
            get {
                return ResourceManager.GetString("sUsedColors", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version Number.
        /// </summary>
        public static string sVersionNumber {
            get {
                return ResourceManager.GetString("sVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View.
        /// </summary>
        public static string sView {
            get {
                return ResourceManager.GetString("sView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Width (X).
        /// </summary>
        public static string sWidth_InBracketX {
            get {
                return ResourceManager.GetString("sWidth_InBracketX", resourceCulture);
            }
        }
    }
}
